apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/corlovito/pollar_deployment/tree/main/catalog_service/staging/?ref=main


configMapGenerator:
- behavior: merge
  files:
  - application-staging.yml
  name: catalog-config

images:
- name: catalog-service
  newName: ghcr.io/corlovito/spring_k8s
  newTag: chapter_14

replicas:
- count: 2
  name: catalog-service
patches:
- path: patch-env.yml
